version: "3.8"

services:
  actors-service:
    build: ./actors-service
    restart: always
    ports:
      - "8080:8080"
    networks:
      - ag53-network
  
  movies-service:
    build: ./movies-service
    restart: always
    ports:
      - "8081:8081"
    networks:
      - ag53-network
  
  acting-service:
    build: ./acting
    restart: always
    ports:
      - "8082:8082"
    networks:
      - ag53-network
    depends_on: [ actors-service, movies-service ]

networks:
  ag53-network:
    name: ag53-network
    driver: bridge
    external: true
