version: "3.8"

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-01-29T03-56-32Z
    container_name: minio
    hostname: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    env_file:
      - .env
    command: server --console-address ":9001" /data
    networks:
      - ag53-network
      
networks:
  ag53-network:
    name: ag53-network
    driver: bridge
    external: true
